/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:990fef42-d6a1-4d27-9c6c-479569ffdce5',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_biMepTpwK',
  aws_user_pools_web_client_id: '7vnnudnuutsm22jt3fbr1pilf5',
  oauth: {
    domain: 'parkyourselfwebapp0c5e8d3a-0c5e8d3a-dev.auth.us-east-1.amazoncognito.com',
    scope: ['phone', 'email', 'openid', 'profile', 'aws.cognito.signin.user.admin'],
    redirectSignIn:
      'https://d31ww6a0jzwr1h.cloudfront.net/,parkyourself://,https://d36x3gddhpmslp.cloudfront.net/,http://localhost:3000/',
    redirectSignOut:
      'https://d31ww6a0jzwr1h.cloudfront.net/,parkyourself://,https://d36x3gddhpmslp.cloudfront.net/,http://localhost:3000/',
    responseType: 'code'
  },
  federationTarget: 'COGNITO_USER_POOLS',
  aws_user_files_s3_bucket: 'parkyourselfbucket154227-dev',
  aws_user_files_s3_bucket_region: 'us-east-1',
  aws_appsync_graphqlEndpoint:
    'https://afavdr6275bqnfrrp3hir7pwzi.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-ui2jxwmyajgozkoh7cdrpfroqu'
};

export default awsmobile;
